version: "3"

services:
  tcm:
    image: lausi95/tennis-court-manager
    networks: [traefik]
    env_file: [tcm.env]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tcm.rule=Host(`tennislichtenberg.de`)
      - traefik.http.routers.tcm.entrypoints=websecure
      - traefik.http.routers.tcm.tls.certresolver=letsencrypt

  mongodb:
    image: mongo
    networks: [traefik]
    env_file: [mongo.env]
    volumes: [tcm-mongodb:/etc/mongodb]
    restart: unless-stopped

networks:
  traefik:
    external: true
    name: traefik

volumes:
  tcm-mongodb:
